[package]
name = "mid-brownie-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
gxhash = { version = "3.4.1" }
plotters = "0.3.7"

[[bin]]
name = "2d"
path = "src/2d.rs"

[[bin]]
name = "3d"
path = "src/3d.rs"
